import Head from 'next/head'
import { Button, Tooltip, Card, Input, Space, Switch, Badge } from 'antd';
import { SearchOutlined, AudioOutlined } from '@ant-design/icons';

const { Search } = Input;

const suffix = (
  <AudioOutlined
    style={{
      fontSize: 16,
      color: '#1890ff',
    }}
  />
);

const onSearch = value => console.log(value);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="main-block">
        {/*Buttons*/}
        <div className="site-card-border-less-wrapper">
          <Card title="Primary buttons width icons" bordered={false} style={{ width: 450 }}>
            <Tooltip title="search">
              <Button type="primary" shape="circle" icon={<SearchOutlined />} />
            </Tooltip>
            <Button type="primary" shape="circle">
              A
            </Button>
            <Button type="primary" icon={<SearchOutlined />}>
              Search
            </Button>
            <Tooltip title="search">
              <Button shape="circle" icon={<SearchOutlined />} />
            </Tooltip>
            <Button icon={<SearchOutlined />}>Search</Button>
            <br />
            <Tooltip title="search">
              <Button shape="circle" icon={<SearchOutlined />} />
            </Tooltip>
            <Button icon={<SearchOutlined />}>Search</Button>
            <Tooltip title="search">
              <Button type="dashed" shape="circle" icon={<SearchOutlined />} />
            </Tooltip>
            <Button type="dashed" icon={<SearchOutlined />}>
              Search
            </Button>
            <Button icon={<SearchOutlined />} href="https://www.google.com" />
            <br />
            <br />
            <Tooltip title="search">
              <Button type="primary" shape="circle" icon={<SearchOutlined />} size="large" />
            </Tooltip>
            <Button type="primary" shape="circle" size="large">
              A
            </Button>
            <Button type="primary" icon={<SearchOutlined />} size="large">
              Search
            </Button>
            <Tooltip title="search">
              <Button shape="circle" icon={<SearchOutlined />} size="large" />
            </Tooltip>
            <Button icon={<SearchOutlined />} size="large">
              Search
            </Button>
            <br />
            <Tooltip title="search">
              <Button shape="circle" icon={<SearchOutlined />} size="large" />
            </Tooltip>
            <Button icon={<SearchOutlined />} size="large">
              Search
            </Button>
            <Tooltip title="search">
              <Button type="dashed" shape="circle" icon={<SearchOutlined />} size="large" />
            </Tooltip>
            <Button type="dashed" icon={<SearchOutlined />} size="large">
              Search
            </Button>
            <Button icon={<SearchOutlined />} size="large" href="https://www.google.com" />
          </Card>
        </div>
        <div className="site-card-border-less-wrapper">
          <Card title="Primary buttons width icons" bordered={false} style={{ width: 500 }}>
            <Button type="primary" danger>
              Primary
            </Button>
            <Button danger>Default</Button>
            <Button type="dashed" danger>
              Dashed
            </Button>
            <Button type="text" danger>
              Text
            </Button>
            <Button type="link" danger>
              Link
            </Button>
          </Card>
        </div>
        {/*Inputs*/}
        <div className="site-card-border-less-wrapper">
          <Card title="Inputs" bordered={false} style={{ width: 500 }}>
            <Space direction="vertical">
              <Search placeholder="input search text" onSearch={onSearch} style={{ width: 200 }} />
              <Search placeholder="input search text" allowClear onSearch={onSearch} style={{ width: 200 }} />
              <Search
                addonBefore="https://"
                placeholder="input search text"
                allowClear
                onSearch={onSearch}
                style={{ width: 304 }}
              />
              <Search placeholder="input search text" onSearch={onSearch} enterButton />
              <Search
                placeholder="input search text"
                allowClear
                enterButton="Search"
                size="large"
                onSearch={onSearch}
              />
              <Search
                placeholder="input search text"
                enterButton="Search"
                size="large"
                suffix={suffix}
                onSearch={onSearch}
              />
            </Space>
          </Card>
        </div>
        {/*Inputs*/}
        <div className="site-card-border-less-wrapper">
          <Card title="Other" bordered={false} style={{ width: 500 }}>
            <Switch defaultChecked />
            <br />
            <Switch size="small" defaultChecked />
            <br />
            <br />
            <Badge.Ribbon text="Hippies">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="pink">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="red">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="cyan">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="green">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="purple">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="volcano">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
            <Badge.Ribbon text="Hippies" color="magenta">
              <Card title="Pushes open the window" size="small">
                and raises the spyglass.
              </Card>
            </Badge.Ribbon>
          </Card>
        </div>
      </main>
    
    </div>
  )
}
